baseurl         = "/"
theme           = "sp-minimal"
languageCode    = "en-us"
title           = "CoMCoR"
disqusShortname = ""
paginate        = 5
ignoreFiles     = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  title       = "CoMCoR"
  subtitle    = "The Impact of Comorbidities on Colorectal and Lung Cancer Treatment and Time to Surgery: A High-Resolution Population-Based Study"
  copyright   = "Released under the MIT license."
  authorImage = "logo.png"

  #"single" or "multi"
  renderType = "single"
  #"simple" or "original"
  themeStyle = "simple"

  googleAnalytics = "UA-122924444-1"

  name = ""
  description = "Comorbidities and colorectal cancer"
  pageNotFoundTitle = "404 - Page not found"